# -*- coding: utf-8 -*-
"""Graficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Assfw_i8etnNNLwRDgp-Q80YMGOW1xhA

# Código Para gerar os gráficos e dashboards
"""
  
pip install -r requirements.txt

import pandas as pd
import plotly.express as px

# Carregando a nossa base de dados, como está em csv, não precisaremos importar json, apenas o pandas para essa leitura.
caminho_arquivo = "US_Crime_Rates_1960_2014 1.csv"
df = pd.read_csv(caminho_arquivo)

def format_number(value):
    """Função para formatar números."""
    if value < 1000:
        return f'{value}'
    elif value < 1000000:
        return f'{value/1000:.1f} mil'
    else:
        return f'{value/1000000:.1f} milhões'

# Convertendo a coluna 'Ano' para o tipo datetime
df['Ano'] = pd.to_datetime(df['Ano'], format='%Y')

# Calculando a soma de crimes para cada ano
df['Total_Crimes'] = df[['Propriedade', 'Homicidio', 'Estupro', 'Roubo_Residencia',
                          'Assalto_Agravante', 'Furto_Residencia', 'Furto_Roubo_Geral',
                          'Roubo_Veiculo']].sum(axis=1)

# Calculando a porcentagem de cada tipo de crime para cada ano
for col in ['Propriedade', 'Homicidio', 'Estupro', 'Roubo_Residencia',
            'Assalto_Agravante', 'Furto_Residencia', 'Furto_Roubo_Geral', 'Roubo_Veiculo']:
    df[col + '_Porcentagem'] = (df[col] / df['Total_Crimes']) * 100

# Agrupando os dados por década e calculando a média das porcentagens de cada tipo de crime
df['Decada'] = pd.cut(df['Ano'], bins=pd.interval_range(start=df['Ano'].min(), end=df['Ano'].max(), freq='10Y'))
df_decadas = df.groupby('Decada').mean()

# Calcular a soma de crimes por década
df_agrupado_decadas = df.groupby('Decada')['Total'].sum().reset_index()
df_agrupado_decadas['Decada'] = df_agrupado_decadas['Decada'].astype(str)

# Criar o gráfico de barras
grafico_crimes_por_decada = px.bar(
    df_agrupado_decadas,
    x='Decada',
    y='Total',
    labels={'Total': 'Total de Crimes', 'Decada': 'Década'},
    title='Total de Crimes por Década'
)


# Testando exibição do gráfico
#grafico_crimes_populacao.show()
